# Generated by Django 4.1 on 2024-02-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NASA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
